/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTutorialsIndexRouteImport } from './routes/app/tutorials/index'
import { Route as AppTipsIndexRouteImport } from './routes/app/tips/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSearchIndexRouteImport } from './routes/app/search/index'
import { Route as AppRecipesIndexRouteImport } from './routes/app/recipes/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppNotesIndexRouteImport } from './routes/app/notes/index'
import { Route as AppLivesIndexRouteImport } from './routes/app/lives/index'
import { Route as AppHistoryIndexRouteImport } from './routes/app/history/index'
import { Route as AppFirstStepsIndexRouteImport } from './routes/app/first-steps/index'
import { Route as AppFavoritesIndexRouteImport } from './routes/app/favorites/index'
import { Route as AppFaqIndexRouteImport } from './routes/app/faq/index'
import { Route as AppCalendarIndexRouteImport } from './routes/app/calendar/index'
import { Route as AppVideosVideoIdRouteImport } from './routes/app/videos/$videoId'
import { Route as AppRecipesRecipeIdRouteImport } from './routes/app/recipes/$recipeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialsIndexRoute = AppTutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => AppRoute,
} as any)
const AppTipsIndexRoute = AppTipsIndexRouteImport.update({
  id: '/tips/',
  path: '/tips/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRoute,
} as any)
const AppLivesIndexRoute = AppLivesIndexRouteImport.update({
  id: '/lives/',
  path: '/lives/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryIndexRoute = AppHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AppRoute,
} as any)
const AppFirstStepsIndexRoute = AppFirstStepsIndexRouteImport.update({
  id: '/first-steps/',
  path: '/first-steps/',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesIndexRoute = AppFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqIndexRoute = AppFaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosVideoIdRoute = AppVideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdRoute = AppRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/recipes/$recipeId': typeof AppRecipesRecipeIdRoute
  '/app/videos/$videoId': typeof AppVideosVideoIdRoute
  '/app/calendar/': typeof AppCalendarIndexRoute
  '/app/faq/': typeof AppFaqIndexRoute
  '/app/favorites/': typeof AppFavoritesIndexRoute
  '/app/first-steps/': typeof AppFirstStepsIndexRoute
  '/app/history/': typeof AppHistoryIndexRoute
  '/app/lives/': typeof AppLivesIndexRoute
  '/app/notes/': typeof AppNotesIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/recipes/': typeof AppRecipesIndexRoute
  '/app/search/': typeof AppSearchIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tips/': typeof AppTipsIndexRoute
  '/app/tutorials/': typeof AppTutorialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/recipes/$recipeId': typeof AppRecipesRecipeIdRoute
  '/app/videos/$videoId': typeof AppVideosVideoIdRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/faq': typeof AppFaqIndexRoute
  '/app/favorites': typeof AppFavoritesIndexRoute
  '/app/first-steps': typeof AppFirstStepsIndexRoute
  '/app/history': typeof AppHistoryIndexRoute
  '/app/lives': typeof AppLivesIndexRoute
  '/app/notes': typeof AppNotesIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/recipes': typeof AppRecipesIndexRoute
  '/app/search': typeof AppSearchIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/tips': typeof AppTipsIndexRoute
  '/app/tutorials': typeof AppTutorialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/recipes/$recipeId': typeof AppRecipesRecipeIdRoute
  '/app/videos/$videoId': typeof AppVideosVideoIdRoute
  '/app/calendar/': typeof AppCalendarIndexRoute
  '/app/faq/': typeof AppFaqIndexRoute
  '/app/favorites/': typeof AppFavoritesIndexRoute
  '/app/first-steps/': typeof AppFirstStepsIndexRoute
  '/app/history/': typeof AppHistoryIndexRoute
  '/app/lives/': typeof AppLivesIndexRoute
  '/app/notes/': typeof AppNotesIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/recipes/': typeof AppRecipesIndexRoute
  '/app/search/': typeof AppSearchIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tips/': typeof AppTipsIndexRoute
  '/app/tutorials/': typeof AppTutorialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/recipes/$recipeId'
    | '/app/videos/$videoId'
    | '/app/calendar/'
    | '/app/faq/'
    | '/app/favorites/'
    | '/app/first-steps/'
    | '/app/history/'
    | '/app/lives/'
    | '/app/notes/'
    | '/app/profile/'
    | '/app/recipes/'
    | '/app/search/'
    | '/app/settings/'
    | '/app/tips/'
    | '/app/tutorials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/recipes/$recipeId'
    | '/app/videos/$videoId'
    | '/app/calendar'
    | '/app/faq'
    | '/app/favorites'
    | '/app/first-steps'
    | '/app/history'
    | '/app/lives'
    | '/app/notes'
    | '/app/profile'
    | '/app/recipes'
    | '/app/search'
    | '/app/settings'
    | '/app/tips'
    | '/app/tutorials'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/recipes/$recipeId'
    | '/app/videos/$videoId'
    | '/app/calendar/'
    | '/app/faq/'
    | '/app/favorites/'
    | '/app/first-steps/'
    | '/app/history/'
    | '/app/lives/'
    | '/app/notes/'
    | '/app/profile/'
    | '/app/recipes/'
    | '/app/search/'
    | '/app/settings/'
    | '/app/tips/'
    | '/app/tutorials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutorials/': {
      id: '/app/tutorials/'
      path: '/tutorials'
      fullPath: '/app/tutorials/'
      preLoaderRoute: typeof AppTutorialsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tips/': {
      id: '/app/tips/'
      path: '/tips'
      fullPath: '/app/tips/'
      preLoaderRoute: typeof AppTipsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search/': {
      id: '/app/search/'
      path: '/search'
      fullPath: '/app/search/'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recipes/': {
      id: '/app/recipes/'
      path: '/recipes'
      fullPath: '/app/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes/': {
      id: '/app/notes/'
      path: '/notes'
      fullPath: '/app/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lives/': {
      id: '/app/lives/'
      path: '/lives'
      fullPath: '/app/lives/'
      preLoaderRoute: typeof AppLivesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history/': {
      id: '/app/history/'
      path: '/history'
      fullPath: '/app/history/'
      preLoaderRoute: typeof AppHistoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/first-steps/': {
      id: '/app/first-steps/'
      path: '/first-steps'
      fullPath: '/app/first-steps/'
      preLoaderRoute: typeof AppFirstStepsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites/': {
      id: '/app/favorites/'
      path: '/favorites'
      fullPath: '/app/favorites/'
      preLoaderRoute: typeof AppFavoritesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faq/': {
      id: '/app/faq/'
      path: '/faq'
      fullPath: '/app/faq/'
      preLoaderRoute: typeof AppFaqIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar/': {
      id: '/app/calendar/'
      path: '/calendar'
      fullPath: '/app/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/videos/$videoId': {
      id: '/app/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/app/videos/$videoId'
      preLoaderRoute: typeof AppVideosVideoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recipes/$recipeId': {
      id: '/app/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/app/recipes/$recipeId'
      preLoaderRoute: typeof AppRecipesRecipeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppRecipesRecipeIdRoute: typeof AppRecipesRecipeIdRoute
  AppVideosVideoIdRoute: typeof AppVideosVideoIdRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppFaqIndexRoute: typeof AppFaqIndexRoute
  AppFavoritesIndexRoute: typeof AppFavoritesIndexRoute
  AppFirstStepsIndexRoute: typeof AppFirstStepsIndexRoute
  AppHistoryIndexRoute: typeof AppHistoryIndexRoute
  AppLivesIndexRoute: typeof AppLivesIndexRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTipsIndexRoute: typeof AppTipsIndexRoute
  AppTutorialsIndexRoute: typeof AppTutorialsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppRecipesRecipeIdRoute: AppRecipesRecipeIdRoute,
  AppVideosVideoIdRoute: AppVideosVideoIdRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppFaqIndexRoute: AppFaqIndexRoute,
  AppFavoritesIndexRoute: AppFavoritesIndexRoute,
  AppFirstStepsIndexRoute: AppFirstStepsIndexRoute,
  AppHistoryIndexRoute: AppHistoryIndexRoute,
  AppLivesIndexRoute: AppLivesIndexRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTipsIndexRoute: AppTipsIndexRoute,
  AppTutorialsIndexRoute: AppTutorialsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
